context:
  name: plopp
  version: 25.7.1
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/plopp-${{ version }}.tar.gz
    sha256: c5030b8f227f75c419684b2975bd5dc77a98682190987cff542848375a786fff

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.8
    - scipp >=25.5.0
    - lazy_loader >=0.4
    - ipympl > 0.8.4
    - pythreejs >= 2.4.1
    - mpltoolbox >= 24.6.0
    - ipywidgets >= 8.1.0
    - python-graphviz >= 0.20.3

tests:
  - python:
      imports:
        - plopp
      python_version: ${{ python_min }}.*

about:
  homepage: https://scipp.github.io/plopp/
  summary: Visualization library for Scipp
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scipp
    - MridulS
