context:
  version: 24.10.0
  python_min: "3.10"

package:
  name: plopp
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/p/plopp/plopp-${{ version }}.tar.gz
  sha256: 463ae5a95f13a7c1efede9950ae9cc29ad7b2b88d978b49a67399ad34d2f6880

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
  - python ${{ python_min }}.*
  - pip
  - setuptools
  run:
  - python >=${{ python_min }}
  - matplotlib-base >=3.5
  - scipp

tests:
- python:
    imports:
    - plopp
    python_version: ${{ python_min }}.*

about:
  homepage: https://scipp.github.io/plopp/
  summary: Visualization library for Scipp
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
