context:
  version: "25.3.0"
  python_min: "3.10"

package:
  name: plopp
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/plopp/plopp-${{ version }}.tar.gz
    sha256: f666e3cf8ccf442b1b825f56d1414902666230dbdf00dd428a7e3519ebb61d30

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.5
    - scipp
    - lazy_loader

tests:
  - python:
      imports:
        - plopp
      python_version: ${{ python_min }}.*

about:
  homepage: https://scipp.github.io/plopp/
  summary: Visualization library for Scipp
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
    - jl-wynen
    - SimonHeybrock
    - YooSunYoung
    - jokasimr
    - nvaytet
