context:
  version: "25.2.0"
  python_min: "3.10"

package:
  name: plopp
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/plopp/plopp-${{ version }}.tar.gz
    sha256: 931dc3f59d62c3c9d211cf4c3dd6b88993a5dfb4e94c6bfce7aec374d831fdc6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.5
    - scipp

tests:
  - python:
      imports:
        - plopp
      python_version: ${{ python_min }}.*

about:
  homepage: https://scipp.github.io/plopp/
  summary: Visualization library for Scipp
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
